### ISSUE TITLE
Insufficient bitsize for MOV opcode

### ISSUE THREAD

**Issue by mukheshpugal** [aklsh/Hephaestus#3]
The MOV opcode is *11 loc_a(7bits) loc_b(7bits)*. This way of adressing cannot cover 256 lines of data.<br/>
One way to fix this would be to use data in registers as locations. That is, formatting the opcode as *11 0000 aaa bbb 000 0*.

**Comment by aklsh** [comment]
That’s a great idea. Maybe we’ll call the current MOV instruction as MOVI, and maybe implement all possible combinations like register-address, address-address, register-register etc.

**Comment by mukheshpugal** [comment]
Address-address won't work.<br/>
Also, do we need so many combos? I hope we dont run out of opcodes for other misc operations.

**Comment by aklsh** [comment]
I mean, address-address will work if both are 7bit addresses. This has to be taken care when programming.
It’s only 3 combinations. The reason is easier programming.

**Comment by aklsh** [comment]
I'll close this issue. Open this if there is anything related
